sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

script:
  - composer install --prefer-dist --no-interaction --no-progress
  - git clone https://github.com/joomla/joomla-cms.git -b master /tmp/joomla-cms
  - composer install -d /tmp/joomla-cms
  - ./vendor/bin/phpunit --configuration ci/phpunit.ci.xml